import type { Theme } from "theme-ui";

export const theme: Theme = {
  fonts: {
    ubuntu: "Ubuntu",
    Inter: "Inter",
    roboto: "Roboto",
    notoSans: "Noto Sans",
    openSans: "Open Sans",
    poppins: "Poppins",
    hind: "Hind",
    lato: "Lato",
    familjenGrotesk: "Familjen Grotesk",
    schibstedGrotesk: "Schibsted Grotesk",
    dmSans: "'DM Sans', 'DM Sans Placeholder', sans-serif",
    Arimo: "'Arimo', sans-serif",
    SpaceGrotesk: "'Space Grotesk', sans-serif",
    Montserrat: "'Montserrat', sans-serif",
    Josefin: "'Josefin Sans', sans-serif",
  },
  fontWeights: {
    light: 300,
    regular: 400,
    medium: 500,
    demi: 600,
    semiBold: 700,
    extraBold: 900,
    large: 950,
  },
  colors: {
    primary: "#297189",
    orange: "#f1b43ed9",
    primaryText: "#303030",
    secondary: "#00C6B7",
    secondary20: "rgba(0, 198, 183, 0.20)",
    tertiary: "#DEF0F6",
    accentColor1: "#2174D4",
    accentColor2: "#FD3A3A",
    accentColor60: "rgba(253, 58, 58, 0.9)",
    accent: "#658C98",
    accentFlag: "#EB0B0B",
    accentStatus: "#FFE5A0",
    accentPrice: "#097AFD",
    neutral: "#EAEAEA",
    neutral3: "#DBE3E8",
    neutral6: "#F2F2F2",
    neutral7: "#EEEEEE",
    neutralGrey: "#A6A6A6",
    white: "#FFFFFF",
    black: "#000",
    grey1: "#727272",
    grey2: "#737373",
    muted: "#858585",
    black2: "#222",
  },
  text: {
    Primary16Medium125: {
      fontFamily: "poppins",
      fontWeight: "medium",
      fontSize: 16,
      lineHeight: "125%",
      color: "white",
    },
    Primary18Medium125: {
      fontFamily: "poppins",
      fontWeight: "medium",
      fontSize: 17,
      lineHeight: "125%",
      color: "#ff8928",
    },
    Montserrat16Medium125: {
      fontFamily: "Montserrat",
      fontWeight: "demi",
      fontSize: 16,
      lineHeight: "125%",
      color: "grey1",
      "&:hover": {
        color: "orange",
      },
    },
    Montserrat15Medium125: {
      fontFamily: "Montserrat",
      fontWeight: "medium",
      fontSize: 16,
      lineHeight: "125%",
      color: "grey1",
      "&:hover": {
        color: "orange",
      },
    },
    Secondary16Demi125: {
      fontFamily: "notoSans",
      fontWeight: "demi",
      fontSize: 16,
      lineHeight: "125%",
      color: "orange",
    },
    DMSans28SemiBold125: {
      fontFamily: "dmSans",
      fontWeight: "semiBold",
      fontSize: 28,
      lineHeight: "125%",
      fontStyle: "normal",
      color: "#323232",
      letterSpacing: ["-1px", "-2px", "-2px", "-2px", "-2px"],
    },
    DMSans28SemiBold2: {
      fontFamily: "dmSans",
      fontWeight: "demi",
      fontSize: 28,
      lineHeight: "125%",
      fontStyle: "normal",
      color: "white",
      letterSpacing: "-1px",
    },
    DMSans22SemiBold125: {
      fontFamily: "dmSans",
      fontWeight: "semiBold",
      fontSize: [20, 21, 22, 23, 23],
      lineHeight: "125%",
      fontStyle: "normal",
      color: "grey1",
      letterSpacing: ["-1px", "-1.1px", "-1.2px", "-1.2px", "-1.2px"],
    },
    DMSans22Medium125: {
      fontFamily: "dmSans",
      fontWeight: "medium",
      fontSize: 22,
      lineHeight: "1.2em",
      fontStyle: "normal",
      color: "grey1",
      letterSpacing: "-1.2px",
    },
    DMSans26Medium3: {
      fontFamily: "dmSans",
      fontWeight: "medium",
      fontSize: 26,
      lineHeight: "1.3em",
      fontStyle: "normal",
      color: "grey1",
      letterSpacing: "-1.5px",
    },
    DMSans26SemiBold3: {
      fontFamily: "dmSans",
      fontWeight: "semiBold",
      fontSize: 26,
      lineHeight: "1.3em",
      fontStyle: "normal",
      color: "orange",
      letterSpacing: "-1.1px",
    },
    DMSans26Medium125: {
      fontFamily: "dmSans",
      fontWeight: "medium",
      fontSize: [22, 24, 25, 26, 26],
      lineHeight: "125%",
      fontStyle: "normal",
      color: "orange",
      letterSpacing: ["-1.2px", "-1.5px", "-1.5px", "-1.5px", "-1.5px"],
    },
    DMSans16Medium125: {
      fontFamily: "dmSans",
      fontWeight: "medium",
      fontSize: 16,
      lineHeight: "125%",
      color: "#bcbab3d9",
      letterSpacing: "-1px",
    },
    DMSans20Demi12em: {
      fontFamily: "dmSans",
      fontWeight: "demi",
      fontSize: 18,
      lineHeight: "1.4em",
      color: "grey1",
    },
  },
  buttons: {
    primary: {
      background: "rgb(50, 50, 50)",
      padding: "10px 20px",
      borderRadius: "100px",
      outline: "unset",
      fontSize: [16, 16, 16, 16, 16, 18, 18],
      lineHeight: ["20px"],
      fontFamily: "notoSans",
      fontWeight: "medium",
      border: "unset",
      color: "white",
      ":hover": {
        background: "orange",
        transition: "background-color 0.5s ease",
      },
      ":focus": {
        border: "1px solid #00C6B7",
      },
      ":active": {
        backgroundColor: "secondary",
      },
      ":disabled": {
        backgroundColor: "#EEEEEE",
        color: "#A6A6A6",
        cursor: "not-allowed",
      },
    },
    downLoadResumeBtn: {
      background: "rgb(50, 50, 50)",
      padding: "8px 16px",
      borderRadius: "100px",
      border: "unset",
      fontSize: [16, 16, 16, 16, 16, 18, 18],
      lineHeight: ["20px"],
      fontFamily: "dmSans",
      letterSpacing: "-1px",
      fontWeight: "semiBold",
      maxWidth: "157px",
      outline: "unset",
      color: "white",
      ":hover": {
        background: "orange",
        transition: "background-color 0.5s ease",
      },
      ":focus": {
        border: "1px solid #00C6B7",
      },
      ":active": {
        backgroundColor: "secondary",
      },
      ":disabled": {
        backgroundColor: "#EEEEEE",
        color: "#A6A6A6",
        cursor: "not-allowed",
      },
    },
  },
  styles: {
    resumeCardItemContainer: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      fontFamily: "dmSans",
      fontWeight: "semiBold",
      fontSize: 23,
      lineHeight: "125%",
      fontStyle: "normal",
      cursor: "pointer",
      color: "grey1",
      letterSpacing: "-1.2px",
      ":hover": {
        color: "rgb(241, 180, 62)",
      },
    },
  },
};
