import type { Theme } from "theme-ui";

export const theme: Theme = {
  fonts: {
    ubuntu: "Ubuntu",
    Inter: "Inter",
    roboto: "Roboto",
    notoSans: "Noto Sans",
    openSans: "Open Sans",
    poppins: "Poppins",
    hind: "Hind",
    lato: "Lato",
    familjenGrotesk: "Familjen Grotesk",
    schibstedGrotesk: "Schibsted Grotesk",
    dmSans: "DM Sans",
  },
  fontWeights: {
    light: 300,
    regular: 400,
    medium: 500,
    demi: 600,
    semiBold: 700,
    extraBold: 900,
    large: 950,
  },
  colors: {
    primary: "#297189",
    orange: "#f1b43e",
    primaryText: "#303030",
    secondary: "#00C6B7",
    secondary20: "rgba(0, 198, 183, 0.20)",
    tertiary: "#DEF0F6",
    accentColor1: "#2174D4",
    accentColor2: "#FD3A3A",
    accentColor60: "rgba(253, 58, 58, 0.9)",
    accent: "#658C98",
    accentFlag: "#EB0B0B",
    accentStatus: "#FFE5A0",
    accentPrice: "#097AFD",
    neutral: "#EAEAEA",
    neutral3: "#DBE3E8",
    neutral6: "#F2F2F2",
    neutral7: "#EEEEEE",
    neutralGrey: "#A6A6A6",
    white: "#FFFFFF",
    black: "#000",
    grey1: "#F1F1F1",
    grey2: "#737373",
    muted: "#858585",
    black2: "#222",
  },
  text: {
    Primary16Medium125: {
      fontFamily: "poppins",
      fontWeight: "medium",
      fontSize: 16,
      lineHeight: "125%",
      color: "white",
    },
    Primary18Medium125: {
      fontFamily: "poppins",
      fontWeight: "medium",
      fontSize: 17,
      lineHeight: "125%",
      color: "#ff8928",
    },
    Secondary16Medium125: {
      fontFamily: "schibstedGrotesk",
      fontWeight: "demi",
      fontSize: 16,
      lineHeight: "125%",
      color: "#727272",
      "&:hover": {
        color: "orange",
      },
    },
    Secondary16Demi125: {
      fontFamily: "notoSans",
      fontWeight: "demi",
      fontSize: 16,
      lineHeight: "125%",
      color: "orange",
    },
    DMSans28SemiBold125: {
      fontFamily: "dmSans",
      fontWeight: "semiBold",
      fontSize: 28,
      lineHeight: "125%",
      fontStyle: "normal",
      color: "orange",
      letterSpacing: "-1px",
    },
  },
  buttons: {
    primary: {
      background: "rgb(50, 50, 50)",
      padding: "10px 20px",
      borderRadius: "100px",
      fontSize: [16, 16, 16, 16, 16, 18, 18],
      lineHeight: ["20px"],
      fontFamily: "notoSans",
      fontWeight: "medium",
      color: "white",
      ":hover": {
        background: "orange",
      },
      ":focus": {
        border: "1px solid #00C6B7",
      },
      ":active": {
        backgroundColor: "secondary",
      },
      ":disabled": {
        backgroundColor: "#EEEEEE",
        color: "#A6A6A6",
        cursor: "not-allowed",
      },
    },
  },
};
